select_origin: directory
files_origin: C:\Users\chauv\Documents\CELF\couffignal\out
nodes_origin: ""
links_origin: ""
nodes_online: ""
links_online: ""
images_origin: ""
export_target: ""
history: false
focus_max: 2
record_types:
  mécanisme:
    fill: "#451322"
    stroke: "#451322"
  cybernétique:
    fill: "#9e4d66"
    stroke: "#9e4d66"
  analogie:
    fill: "#f2b3c7"
    stroke: "#f2b3c7"
  information:
    fill: "#85D4DB"
    stroke: "#85B0DB"
  undefined:
    fill: "#858585"
    stroke: "#858585"
link_types:
  undefined:
    stroke: simple
    color: "#e1e1e1"
record_filters: []
graph_background_color: "#ffffff"
graph_highlight_color: "#ff6a6a"
graph_highlight_on_hover: true
graph_text_size: 10
graph_arrows: true
node_size_method: degree
node_size: 10
node_size_max: 20
node_size_min: 2
attraction_force: 200
attraction_distance_max: 250
attraction_vertical: 0
attraction_horizontal: 0
views: {}
chronological_record_meta: created
record_metas: []
title: Les Machines à penser
author: jmc
description: "Louis Couffignal (1963)"
keywords: []
link_symbol: "![](Icon_External_Link.png)"
csl: ""
bibliography: ""
csl_locale: ""
css_custom: ""
devtools: false
lang: en
name: ""
